name: PR Review Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print review status
        run: echo "A pull request review was submitted!"
